// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcNVAvBXx9C2EVBrjbnRuU7-U-6bCE2Q',
    appId: '1:846194773488:web:cbba94f3b754ef573ae135',
    messagingSenderId: '846194773488',
    projectId: 'shopping-app-8863d',
    authDomain: 'shopping-app-8863d.firebaseapp.com',
    storageBucket: 'shopping-app-8863d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_NBrPhez8y-xiSB0LeFsoQ8jVhigldpA',
    appId: '1:846194773488:android:06a84e22e2de72593ae135',
    messagingSenderId: '846194773488',
    projectId: 'shopping-app-8863d',
    storageBucket: 'shopping-app-8863d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkluX2umJ5wS87WjaP1FOzpe7nctkY9zA',
    appId: '1:846194773488:ios:457b0555a269387f3ae135',
    messagingSenderId: '846194773488',
    projectId: 'shopping-app-8863d',
    storageBucket: 'shopping-app-8863d.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkluX2umJ5wS87WjaP1FOzpe7nctkY9zA',
    appId: '1:846194773488:ios:457b0555a269387f3ae135',
    messagingSenderId: '846194773488',
    projectId: 'shopping-app-8863d',
    storageBucket: 'shopping-app-8863d.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzcNVAvBXx9C2EVBrjbnRuU7-U-6bCE2Q',
    appId: '1:846194773488:web:038bf6e7f49d022c3ae135',
    messagingSenderId: '846194773488',
    projectId: 'shopping-app-8863d',
    authDomain: 'shopping-app-8863d.firebaseapp.com',
    storageBucket: 'shopping-app-8863d.firebasestorage.app',
  );
}
